[package]
name = "racketffi"
version = "0.1.0"
authors = ["Joshua Schappel <jmschappel12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "racketffi"
crate-type = ["cdylib", "staticlib"]


[dependencies]
